#!/bin/bash

# 🚀 COMMANDES ESSENTIELLES - CALENDRIER

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🚀 CALENDRIER AVEC GESTION UTILISATEURS - DÉMARRAGE    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

cd /media/james/DATA1/python/fullCalendar

echo "📋 COMMANDES DISPONIBLES:"
echo ""
echo "1️⃣  DÉMARRER L'APPLICATION (DOCKER - recommandé):"
echo "    $ docker compose up -d --build"
echo ""
echo "    Application (unique): http://localhost/"
echo "    API + Swagger:        http://localhost/docs"
echo "    Login direct:         http://localhost/login"
echo ""
echo "2️⃣  DÉMARRER L'APPLICATION (LOCAL / venv):"
echo "    $ ./start.sh"
echo ""
echo "3️⃣  OUVRIR DANS LE NAVIGATEUR (LOCAL / venv):"
echo "    http://localhost:8001/login"
echo ""
echo "4️⃣  CREDENTIALS ADMIN PAR DÉFAUT:"
echo "    Email:    admin@devops.example.com"
echo "    Password: Admin@123456"
echo ""
echo "5️⃣  SWAGGER UI (API Documentation):"
echo "    Docker: http://localhost/docs"
echo "    Local:  http://localhost:8001/docs"
echo ""
echo "6️⃣  TESTER LES ENDPOINTS:"
echo "    $ source venv/bin/activate && python test_api.py"
echo ""
echo "7️⃣  VALIDER L'IMPLÉMENTATION:"
echo "    $ bash validate_implementation.sh"
echo ""
echo "8️⃣  ARRÊTER L'APPLICATION:"
echo "    Docker: docker compose down"
echo "    Local:  CTRL+C dans le terminal"
echo ""
echo "9️⃣  RÉINITIALISER LA BASE DE DONNÉES:"
echo "    $ ./reset_db.sh"
echo ""
echo "🔟 VOIR LES LOGS:"
echo "    Docker: docker compose logs -f --tail=200 backend"
echo "    Local:  (Affichés dans le terminal de start.sh)"
echo ""
echo "📚 DOCUMENTATION:"
echo "    - QUICK_START.txt              (Ce fichier)"
echo "    - README_INTERFACE.md          (Guide utilisateur)"
echo "    - DOCUMENTATION.md             (Documentation technique)"
echo "    - IMPLEMENTATION_SUMMARY.md    (Résumé implémentation)"
echo "    - FINAL_SUMMARY.md             (Résumé final)"
echo ""
echo "📧 FICHIERS PRINCIPAUX CRÉÉS:"
echo ""
echo "   Backend:"
echo "    ✅ app/security.py              JWT & password utilities"
echo "    ✅ app/schemas_auth.py          Pydantic auth schemas"
echo "    ✅ app/crud_auth.py             Auth CRUD operations"
echo "    ✅ app/routers/auth.py          Auth endpoints"
echo ""
echo "   Frontend:"
echo "    ✅ frontend/                    SPA React + Bulma"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🎯 PROCHAINES ÉTAPES:"
echo ""
echo "   Docker:"
echo "     1. Lancer: docker compose up -d --build"
echo "     2. Ouvrir: http://localhost/"
echo ""
echo "   Local (venv):"
echo "     1. Lancer: ./start.sh"
echo "     2. Ouvrir: http://localhost:8001/login"
echo ""
echo "   Identifiants: admin@devops.example.com / Admin@123456"
echo ""
echo "════════════════════════════════════════════════════════════"
